### ISSUE TITLE
demo rake task features

### ISSUE THREAD

**Issue by philschatz** [openstax/tutor-server#217]
This is mostly here so Dante/Kevin can check off (or remove)

# TaskPlans:

- [x] >= 1 iReading with stats
- [x] >= 1 homework with stats
- [x] make some date ranges overlap
- [x] make 1 span to another month

# Tasks

- [x] 1 In-progress iReading (or the same task twice) with:
  - [x] 1 step with "Try another"
  - [x] 1 step with "Remind me"
- [x] 1 Graded task with correct/incorrect answers
- [x] 1 Graded task with an unanswered step

- [x] >= 1 HW in the future
- [x] >= 1 iReading in the future

**Comment by Dantemss** [comment]
Greg agreed that this would be good for his tests too, so I'll update the deployment task data to contain these features.

**Comment by Dantemss** [comment]
I'll be adding to https://github.com/openstax/tutor-server/pull/214

**Comment by nathanstitt** [comment]
We also need to make sure that there are both HW and iReadings happening in the current week so that the "This Week" section of the student dashboard has data.

**Comment by Dantemss** [comment]
Done here: https://github.com/openstax/tutor-server/pull/219

**Comment by Dantemss** [comment]
Will address Nathan's comment...

**Comment by Dantemss** [comment]
Nvm, it's done. The third homework opens now (when you run the task) and closes in 1 week. The third iReading opened last week and closes in 1 week.

**Comment by philschatz** [comment]
The plans that are created all have `opens_at` but not `due_at`. Is there a reason for this?

**Comment by Dantemss** [comment]
Fixed here: https://github.com/openstax/tutor-server/pull/222

**Comment by philschatz** [comment]
Demo done!
