### ISSUE TITLE
Tutor Release - 4/7/2021

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor-server#2293]
Code freeze - QA: 3/26/2021
RC Review meeting:  4/1/2021
Code deploy - Staging: 3/29/2021
Code Release - Production: 4/7/2021

### Emergency Preparation 
- [ ] Verify automated RDS backups completed successfully. 
- [ ] Record existing tags for deployed repos 

#### Before Deployment Tasks
- [ ]  
 
###### Only list the repos that are deployed for this release. 
- [ ]  openstax/tutor-deployment @ 
- [ ]  openstax/accounts @  
- [ ]  openstax/exercises @ 
- [ ]  openstax/tutor-js (exercises-js) @ 
- [ ]  openstax/tutor-server @  
- [ ]  openstax/tutor-js @ 
- [ ]  openstax/response-validator @ 
- [ ] openstax/validator-deployment @ 
----------------------------------------------

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment @
- [ ]  openstax/accounts @
- [ ]  openstax/exercises @
- [ ]  openstax/tutor-js (exercises-js) @
- [ ]  openstax/tutor-server @
- [ ]  openstax/tutor-js @

###### Only list the repos that are deployed for this release. 

- [ ]  openstax/tutor-deployment @
- [ ]  openstax/accounts @
- [ ]  openstax/tutor-server @
- [ ]  openstax/tutor-js @

### Migrations
- [ ] Yes 
- [ ] No 

### After Deployment Tasks
- [ ] 

### Emergency (Only filled in if there is a full rollback) 
- [ ] Rename RDS instance of app to be rolled back to `<name>-failed-<date>`
- [ ] Restore RDS snapshot to `<name>`
- [ ] Set Security Group of new RDS instance to match the original instance
- [ ] Deploy previous tags to restore old code. 

## End DevOps Production Deploy
-----------------------------------------------------------------------------------------
### Versions being tested:

On Staging Environment: *Status*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @ X
- [ ]  openstax/accounts @  X
- [ ]  openstax/exercises @ 
- [ ]  openstax/tutor-js (exercises-js) @ X
- [ ]  openstax/tutor-server @  X
- [ ]  openstax/tutor-js @ X
- [ ]  openstax/response-validator @ X
- [ ] openstax/validator-deployment @ X
-----------------------------------------------------------------------------------------

On QA Environment: *Status*
###### Put an X for the repos *not* going out

- [ ]  openstax/tutor-deployment @ v39.0.0
- [ ]  openstax/accounts @  X
- [ ]  openstax/exercises @ v32.0.0
- [ ]  openstax/tutor-js (exercises-js) @ v52.0.0
- [ ]  openstax/tutor-server @  v52.0.0
- [ ]  openstax/tutor-js @  v52.0.0
- [ ]  openstax/response-validator @ X
- [ ] openstax/validator-deployment @ X
-----------------------------------------------------------------------------------------

**Comment by Brooke-Fail** [comment]
All cards have been verified and closed.
